### PR TITLE
Crate linter attributes

### PR DESCRIPTION
**Pull request by uklotzde**
Minor dependency updates and my current standard set of linter attributes.

### CODE REVIEW

**Comment by uklotzde** [comment]
Ping ;)

**Comment by Holzhaus** [comment]
When I merge this into a local branch, pre-commit fails:

```sh
$ git checkout main
$ git checkout -b test
$ git pull https://github.com/uklotzde/triseratops.git crate-linter-attributes
$ pre-commit run --from-ref main --to-ref HEAD
[...]
fmt......................................................................Failed
- hook id: fmt
- exit code: 1

Invalid value for `--edition`
Invalid value for `--edition`
Invalid value for `--edition`
Invalid value for `--edition`
Invalid value for `--edition`

cargo check..............................................................Failed
- hook id: cargo-check
- exit code: 101

   Compiling memchr v2.3.4
   Compiling regex-syntax v0.6.25
    Checking cfg-if v1.0.0
    Checking adler v0.2.3
    Checking minimal-lexical v0.2.1
   Compiling triseratops v0.0.2 (/home/jan/Projects/triseratops)
    Checking byteorder v1.4.2
    Checking unicode-width v0.1.8
    Checking smawk v0.3.0
   Compiling nom v7.1.0
    Checking libc v0.2.82
error: edition 2021 is unstable and only available with -Z unstable-options.

error: could not compile `triseratops`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed

clippy...................................................................Failed
- hook id: clippy
- exit code: 101

   Compiling triseratops v0.0.2 (/home/jan/Projects/triseratops)
   Compiling memchr v2.3.4
   Compiling nom v7.1.0
    Checking crc32fast v1.2.1
    Checking miniz_oxide v0.4.3
error: edition 2021 is unstable and only available with -Z unstable-options.

error: could not compile `triseratops`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by Holzhaus** [comment]
Weird, the 2021 edition was already introduced in #12 but I didn't notice the issues until now :shrug:

**Comment by Holzhaus** [comment]
Ooof, I managed to mess up my local rust install. Switched back to stable rust 1.58.1 from the Arch repos, now everything works fine.

**Review by Holzhaus — APPROVED** [review]

**Pull request merged**
